title: Tayo Ogunbiyi
description: Notes on LLM inference, systems, and software engineering
url: "https://tayoogunbiyi.github.io"

theme: minima
show_excerpts: true
permalink: /:title/

plugins:
  - jekyll-feed